=== addidotlol/terbium/static/schema/meta/v1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://terbium.app/schema/meta/v1.json",
  "title": "Superbird Flash Configuration",
  "description": "Schema for Superbird firmware flashing configuration files",
  "type": "object",
  "required": [
    "name",
    "version",
    "description",
    "steps",
    "metadataVersion"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "Name of the firmware configuration"
    },
    "version": {
      "type": "string",
      "description": "Version of the firmware configuration"
    },
    "description": {
      "type": "string",
      "description": "Description of the firmware configuration"
    },
    "steps": {
      "type": "array",
      "description": "An array of steps to execute during flashing",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "$ref": "#/definitions/identifyStep"
          },
          {
            "$ref": "#/definitions/bulkcmdStep"
          },
          {
            "$ref": "#/definitions/bulkcmdStatStep"
          },
          {
            "$ref": "#/definitions/runStep"
          },
          {
            "$ref": "#/definitions/writeSimpleMemoryStep"
          },
          {
            "$ref": "#/definitions/writeLargeMemoryStep"
          },
          {
            "$ref": "#/definitions/readSimpleMemoryStep"
          },
          {
            "$ref": "#/definitions/readLargeMemoryStep"
          },
          {
            "$ref": "#/definitions/getBootAMLCStep"
          },
          {
            "$ref": "#/definitions/writeAMLCDataStep"
          },
          {
            "$ref": "#/definitions/bl2BootStep"
          },
          {
            "$ref": "#/definitions/validatePartitionSizeStep"
          },
          {
            "$ref": "#/definitions/restorePartitionStep"
          },
          {
            "$ref": "#/definitions/writeBootPartitionStep"
          },
          {
            "$ref": "#/definitions/writeUserAreaStep"
          },
          {
            "$ref": "#/definitions/writeEnvStep"
          },
          {
            "$ref": "#/definitions/logStep"
          },
          {
            "$ref": "#/definitions/waitStep"
          }
        ]
      }
    },
    "variables": {
      "type": "object",
      "description": "Variables to store data between steps",
      "additionalProperties": {
        "type": "integer"
      }
    },
    "metadataVersion": {
      "type": "integer",
      "description": "Version of the metadata format",
      "enum": [
        1,
        2
      ]
    }
  },
  "definitions": {
    "identifyStep": {
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "enum": [
            "identify"
          ]
        },
        "variable": {
          "type": "string"
        }
      }
    },
    "bulkcmdStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "bulkcmd"
          ]
        },
        "value": {
          "type": "string"
        }
      }
    },
    "bulkcmdStatStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "bulkcmdStat"
          ]
        },
        "value": {
          "type": "string"
        },
        "variable": {
          "type": "string"
        }
      }
    },
    "runStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "run"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "address"
          ],
          "properties": {
            "address": {
              "type": "integer"
            },
            "keepPower": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "writeSimpleMemoryStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "writeSimpleMemory"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "address",
            "data"
          ],
          "properties": {
            "address": {
              "type": "integer"
            },
            "data": {
              "$ref": "#/definitions/dataOrFile"
            }
          }
        }
      }
    },
    "writeLargeMemoryStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "writeLargeMemory"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "address",
            "data",
            "blockLength"
          ],
          "properties": {
            "address": {
              "type": "integer"
            },
            "data": {
              "$ref": "#/definitions/dataOrFile"
            },
            "blockLength": {
              "type": "integer"
            },
            "appendZeros": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "readSimpleMemoryStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "readSimpleMemory"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "address",
            "length"
          ],
          "properties": {
            "address": {
              "type": "integer"
            },
            "length": {
              "type": "integer"
            }
          }
        },
        "variable": {
          "type": "string"
        }
      }
    },
    "readLargeMemoryStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "readLargeMemory"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "address",
            "length"
          ],
          "properties": {
            "address": {
              "type": "integer"
            },
            "length": {
              "type": "integer"
            }
          }
        },
        "variable": {
          "type": "string"
        }
      }
    },
    "getBootAMLCStep": {
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "enum": [
            "getBootAMLC"
          ]
        },
        "variable": {
          "type": "string"
        }
      }
    },
    "writeAMLCDataStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "writeAMLCData"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "seq",
            "amlcOffset",
            "data"
          ],
          "properties": {
            "seq": {
              "type": "integer"
            },
            "amlcOffset": {
              "type": "integer"
            },
            "data": {
              "$ref": "#/definitions/dataOrFile"
            }
          }
        }
      }
    },
    "bl2BootStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "bl2Boot"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "bl2",
            "bootloader"
          ],
          "properties": {
            "bl2": {
              "$ref": "#/definitions/dataOrFile"
            },
            "bootloader": {
              "$ref": "#/definitions/dataOrFile"
            }
          }
        }
      }
    },
    "validatePartitionSizeStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "validatePartitionSize"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "variable": {
          "type": "string"
        }
      }
    },
    "restorePartitionStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "restorePartition"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "name",
            "data"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "data": {
              "$ref": "#/definitions/dataOrFile"
            }
          }
        }
      }
    },
    "writeBootPartitionStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "writeBootPartition"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "hwpart",
            "data"
          ],
          "properties": {
            "hwpart": {
              "type": "integer",
              "description": "eMMC boot hwpartition index: 1 = boot0, 2 = boot1",
              "enum": [
                1,
                2
              ]
            },
            "data": {
              "$ref": "#/definitions/dataOrFile"
            }
          }
        }
      }
    },
    "writeUserAreaStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "writeUserArea"
          ]
        },
        "value": {
          "type": "object",
          "required": [
            "lba",
            "data"
          ],
          "properties": {
            "lba": {
              "type": "integer",
              "description": "Absolute LBA on the user area (hwpart 0); sector size is 512 bytes"
            },
            "data": {
              "$ref": "#/definitions/dataOrFile"
            }
          }
        }
      }
    },
    "writeEnvStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "writeEnv"
          ]
        },
        "value": {
          "$ref": "#/definitions/stringOrFile"
        }
      }
    },
    "logStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "log"
          ]
        },
        "value": {
          "type": "string"
        }
      }
    },
    "waitStep": {
      "type": "object",
      "required": [
        "type",
        "value"
      ],
      "properties": {
        "type": {
          "enum": [
            "wait"
          ]
        },
        "value": {
          "oneOf": [
            {
              "type": "object",
              "required": [
                "type",
                "message"
              ],
              "properties": {
                "type": {
                  "enum": [
                    "userInput"
                  ]
                },
                "message": {
                  "type": "string"
                }
              }
            },
            {
              "type": "object",
              "required": [
                "type",
                "time"
              ],
              "properties": {
                "type": {
                  "enum": [
                    "time"
                  ]
                },
                "time": {
                  "type": "integer"
                }
              }
            }
          ]
        }
      }
    },
    "dataOrFile": {
      "oneOf": [
        {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        {
          "type": "object",
          "required": [
            "filePath"
          ],
          "properties": {
            "filePath": {
              "type": "string"
            },
            "encoding": {
              "type": "string"
            }
          }
        }
      ]
    },
    "stringOrFile": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "required": [
            "filePath"
          ],
          "properties": {
            "filePath": {
              "type": "string"
            },
            "encoding": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}

=== addidotlol/terbium/firmware/stock/meta.json
{
	"$schema": "https://terbium.app/schema/meta/v1.json",
	"metadataVersion": 2,
	"name": "Factory Reset to Spotify",
	"version": "8.2.5",
	"description": "Restores the stock Spotify Car Thing firmware, wiping any custom firmware and returning the device to its factory 8.2.5 state.",
	"steps": [
		{
			"type": "log",
			"value": "writing the emergency stock recovery image"
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 0, "data": { "filePath": "unbrick.bin" } }
		},
		{
			"type": "log",
			"value": "restoring stock Spotify firmware 8.2.5"
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 237568, "data": { "filePath": "env.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 270336, "data": { "filePath": "fip_a.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 294912, "data": { "filePath": "fip_b.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 319488, "data": { "filePath": "logo.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 352256, "data": { "filePath": "dtbo_a.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 376832, "data": { "filePath": "dtbo_b.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 401408, "data": { "filePath": "vbmeta_a.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 419840, "data": { "filePath": "vbmeta_b.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 438272, "data": { "filePath": "boot_a.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 487424, "data": { "filePath": "boot_b.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 536576, "data": { "filePath": "system_a.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 1609816, "data": { "filePath": "system_b.dump" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 2683056, "data": { "filePath": "misc.dump" } }
		},
		{
			"type": "log",
			"value": "clearing user data left by previous firmware"
		},
		{
			"type": "writeUserArea",
			"value": {
				"lba": 2715824,
				"data": { "filePath": "zero-settings.bin" },
				"sparse": true
			}
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 3256496, "data": { "filePath": "zero-data.bin" }, "sparse": true }
		},
		{
			"type": "log",
			"value": "restoring stock partition table and bootloader"
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 73728, "data": { "filePath": "mpt.bin" } }
		},
		{
			"type": "writeUserArea",
			"value": { "lba": 0, "data": { "filePath": "bootloader.dump" } }
		},
		{
			"type": "writeBootPartition",
			"value": { "hwpart": 1, "data": { "filePath": "stock-boot-partition.bin" } }
		},
		{
			"type": "writeBootPartition",
			"value": { "hwpart": 2, "data": { "filePath": "stock-boot-partition.bin" } }
		}
	]
}
